# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6258c869b49a7e4fc700cfc2913ab87e51ed3ec1af82cf9381f054611b42ef03bbaa6135ad97ae053a26a21231848042409b486b6b5734f047fc13f434d160f5

test:
  secret_key_base: eee6057bacf09543b157415ce016ffb2f2a425db251f60f3af5b597fa372670bd8e9ce23f3037a3a52f71e729402cd004e123211f15b25a31667ef2924239247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
